INSERT INTO lms.cohort (alias, github_repository, name)
VALUES ('Cohort 21', 'cohort21', 'Cohort 21');
INSERT INTO lms.cohort (alias, github_repository, name)
VALUES ('Cohort 22', 'cohort22', 'Cohort 22');
INSERT INTO lms.cohort (alias, github_repository, name)
VALUES ('Cohort 23', 'cohort23', 'Cohort 23');
INSERT INTO lms.cohort (alias, github_repository, name)
VALUES ('Cohort 23.1', 'cohort23.1', 'Cohort 23.1');
INSERT INTO lms.cohort (alias, github_repository, name)
VALUES ('Cohort 23.2', 'cohort23.2', 'Cohort 23.2');
INSERT INTO lms.cohort (alias, github_repository, name)
VALUES ('Cohort 24', 'cohort24', 'Cohort 24');
INSERT INTO lms.cohort (alias, github_repository, name)
VALUES ('Cohort 25', 'cohort25', 'Cohort 25');
INSERT INTO lms.cohort (alias, github_repository, name)
VALUES ('Cohort 26', 'cohort26', 'Cohort 26');
INSERT INTO lms.cohort (alias, github_repository, name)
VALUES ('Cohort 27', 'cohort27', 'Cohort 27');
INSERT INTO lms.cohort (alias, github_repository, name)
VALUES ('Cohort 28', 'cohort28', 'Cohort 28');
INSERT INTO lms.cohort (alias, github_repository, name)
VALUES ('Cohort 29', 'cohort29', 'Cohort 29');
INSERT INTO lms.cohort (alias, github_repository, name)
VALUES ('Cohort 30', 'cohort30', 'Cohort 30');
INSERT INTO lms.cohort (alias, github_repository, name)
VALUES ('Cohort 31.1', 'cohort31.1', 'Cohort 31.1');
INSERT INTO lms.cohort (alias, github_repository, name)
VALUES ('Cohort 31.2', 'cohort31.2', 'Cohort 31.2');
INSERT INTO lms.cohort (alias, github_repository, name)
VALUES ('Cohort 32', 'cohort32', 'Cohort 32');
INSERT INTO lms.cohort (alias, github_repository, name)
VALUES ('Cohort 33', 'cohort33', 'Cohort 33');
INSERT INTO lms.cohort (alias, github_repository, name)
VALUES ('Cohort 34.1', 'cohort34.1', 'Cohort 34.1');
INSERT INTO lms.cohort (alias, github_repository, name)
VALUES ('Cohort 34.2', 'cohort34.2', 'Cohort 34.2');
INSERT INTO lms.cohort (alias, github_repository, name)
VALUES ('Cohort 34.3', 'cohort34.3', 'Cohort 34.3');
INSERT INTO lms.cohort (alias, github_repository, name)
VALUES ('Cohort 35', 'cohort35', 'Cohort 35');
INSERT INTO lms.cohort (alias, github_repository, name)
VALUES ('Cohort 36', 'cohort36', 'Cohort 36');